// Generated by the admin-dashboard onboarding flow. Do not edit by hand —
// re-run "Add feedback button" in the dashboard to rotate the token.
export const DASHBOARD_FEEDBACK = {
  ingestUrl: "https://feedback.diyhelper.org/api/ingest/feedback",
  ingestToken: "landscape-helper.e57214c58beee857a72bfa1f62aee51ef4e2c19748516dba",
};