// Self-contained beta-feedback floating button. Generated by the admin-dashboard
// onboarding flow. Draggable pill + modal; posts to the dashboard's ingest API.
// No native/expo dependencies — drop it in and render <DashboardFeedbackButton/>
// at the root of your app.
import React, { useRef, useState } from 'react';
import {
  Animated, Modal, PanResponder, Platform, Pressable, StyleSheet, Text, TextInput, View,
} from 'react-native';
import { DASHBOARD_FEEDBACK } from './dashboard-feedback.config';

type Props = {
  /** Current screen/route name; shown to you in the dashboard. */
  screenName?: string;
  appVersion?: string;
  buildNumber?: string;
};

export function DashboardFeedbackButton({ screenName = 'unknown', appVersion, buildNumber }: Props) {
  const [open, setOpen] = useState(false);
  const [text, setText] = useState('');
  const [sending, setSending] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const pan = useRef(new Animated.ValueXY({ x: 0, y: 0 })).current;
  const draggedRef = useRef(false);

  const responder = useRef(
    PanResponder.create({
      onStartShouldSetPanResponder: () => true,
      onMoveShouldSetPanResponder: (_e, g) => Math.abs(g.dx) > 4 || Math.abs(g.dy) > 4,
      onPanResponderGrant: () => { draggedRef.current = false; pan.extractOffset(); },
      onPanResponderMove: (e, g) => {
        if (Math.abs(g.dx) > 4 || Math.abs(g.dy) > 4) draggedRef.current = true;
        Animated.event([null, { dx: pan.x, dy: pan.y }], { useNativeDriver: false })(e, g);
      },
      onPanResponderRelease: () => {
        pan.flattenOffset();
        if (!draggedRef.current) setOpen(true);
      },
    }),
  ).current;

  async function send() {
    if (!text.trim()) { setError('Please enter some feedback.'); return; }
    setSending(true); setError(null);
    try {
      const res = await fetch(DASHBOARD_FEEDBACK.ingestUrl, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'X-Ingest-Token': DASHBOARD_FEEDBACK.ingestToken,
        },
        body: JSON.stringify({
          feedbackText: text.trim(),
          screenName,
          relatesToAi: false,
          appVersion,
          buildNumber,
          platform: Platform.OS,
        }),
      });
      if (!res.ok) throw new Error('HTTP ' + res.status);
      setText(''); setOpen(false);
    } catch (e: any) {
      setError((e && e.message) || 'Failed to send feedback.');
    } finally {
      setSending(false);
    }
  }

  return (
    <View pointerEvents="box-none" style={StyleSheet.absoluteFill}>
      <Animated.View {...responder.panHandlers} style={[styles.wrap, { transform: pan.getTranslateTransform() }]}>
        <Pressable style={styles.pill} onPress={() => setOpen(true)} accessibilityRole="button" accessibilityLabel="Send feedback">
          <Text style={styles.pillText}>Feedback</Text>
        </Pressable>
      </Animated.View>
      <Modal visible={open} transparent animationType="slide" onRequestClose={() => setOpen(false)}>
        <View style={styles.backdrop}>
          <View style={styles.sheet}>
            <Text style={styles.title}>Send feedback</Text>
            <Text style={styles.sub}>On {screenName}. What didn't work, or what could be better?</Text>
            <TextInput
              style={styles.input}
              value={text}
              onChangeText={setText}
              multiline
              editable={!sending}
              placeholder="Your feedback..."
              placeholderTextColor="#9ca3af"
            />
            {error ? <Text style={styles.error}>{error}</Text> : null}
            <View style={styles.actions}>
              <Pressable style={styles.btnGhost} onPress={() => setOpen(false)} disabled={sending}>
                <Text style={styles.btnGhostText}>Cancel</Text>
              </Pressable>
              <Pressable style={styles.btn} onPress={send} disabled={sending}>
                <Text style={styles.btnText}>{sending ? 'Sending...' : 'Send'}</Text>
              </Pressable>
            </View>
          </View>
        </View>
      </Modal>
    </View>
  );
}

const styles = StyleSheet.create({
  wrap: { position: 'absolute', right: 16, bottom: 96, zIndex: 9999, elevation: 9999 },
  pill: {
    backgroundColor: '#2563eb', borderRadius: 24, paddingHorizontal: 16, paddingVertical: 10,
    shadowColor: '#000', shadowOpacity: 0.25, shadowRadius: 6, shadowOffset: { width: 0, height: 2 },
  },
  pillText: { color: '#fff', fontWeight: '600', fontSize: 14 },
  backdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'flex-end' },
  sheet: { backgroundColor: '#fff', borderTopLeftRadius: 16, borderTopRightRadius: 16, padding: 20 },
  title: { fontSize: 18, fontWeight: '700', color: '#111827' },
  sub: { fontSize: 13, color: '#6b7280', marginTop: 4, marginBottom: 12 },
  input: {
    minHeight: 96, borderWidth: 1, borderColor: '#e5e7eb', borderRadius: 10, padding: 12,
    fontSize: 15, color: '#111827', textAlignVertical: 'top',
  },
  error: { color: '#dc2626', marginTop: 8, fontSize: 13 },
  actions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 12, marginTop: 16 },
  btn: { backgroundColor: '#2563eb', borderRadius: 10, paddingHorizontal: 18, paddingVertical: 10 },
  btnText: { color: '#fff', fontWeight: '600' },
  btnGhost: { borderRadius: 10, paddingHorizontal: 18, paddingVertical: 10 },
  btnGhostText: { color: '#6b7280', fontWeight: '600' },
});