<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Sburson.Shared.Backend" Version="0.1.2" />
    <PackageReference Include="AWSSDK.SecretsManager" Version="4.0.4.15" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.5" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.3" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="OpenAI" Version="2.9.1" />
    <PackageReference Include="Sentry.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include=".ebextensions\**" CopyToPublishDirectory="Always" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="LandscapeHelper.Tests" />
  </ItemGroup>

</Project>
